glibc: re-enable nscd build and packaging (#12595)
During initial development of Azure Linux 3.0, the glibc build of nscd was
with no suitable alternative introduced into the distribution for certain
caching, which could typically be fulfilled by sssd.

This change re-enables nscd in the distribution. We will continue to look
at the alternatives during the next major release development cycle.

There is a known nscd build issue in glibc 2.38 when built with -fexceptions.

/usr/bin/ld: /usr/src/azl/BUILD/glibc-build/nscd/gai.o: in function cancel_handler': /usr/src/azl/BUILD/glibc-2.38/nscd/../sysdeps/unix/sysv/linux/check_pf.c:300:(.text+0x1a7c): undefined reference to _Unwind_Resume'
/usr/bin/ld: /usr/src/azl/BUILD/glibc-build/nscd/gai.o:(.data.rel.local.DW.ref.__gcc_personality_v0[DW.ref.__gcc_personality_v0]+0x0): undefined reference to `__gcc_personality_v0'
collect2: error: ld returned 1 exit status
make[2]: *** [../Rules:283: /usr/src/azl/BUILD/glibc-build/nscd/nscd] Error 1
make[2]: Leaving directory '/usr/src/azl/BUILD/glibc-2.38/nscd'
make[1]: *** [Makefile:484: nscd/others] Error 2
make[1]: Leaving directory '/usr/src/azl/BUILD/glibc-2.38'
make: *** [Makefile:9: all] Error 2

This change backports the upstream fix to resolve the build break.

Signed-off-by: Chris Co <chrco@microsoft.com>