qemu: Remove deprecated --enable/disable-avx512f configure options
The avx512f configure option was removed in QEMU 9.1.0 by upstream commit
b3f1ce8a472e7239b196bcb3aaa38738012f23b5 ('meson: remove dead optimization
option') as it was never actually used. This fixes the build failure:

  ERROR: unknown option --disable-avx512f

Signed-off-by: Aadhar Agarwal <aadagarwal@microsoft.com>