revert(51c1d561aa, grub2): re-enable os-prober by default
This reverts commit 51c1d561aa8cabba2da7577dd7a86a56dfbe34cd.

The change broke the build with the following error during %prep:

    /builddir/build/SOURCES/0382-Set-correctly-the-memory-attributes-for-the-kernel-P.patch
    error: patch failed: docs/grub.texi:1552
    error: docs/grub.texi: patch does not apply
    Applying: Revert "templates: Fix user-facing typo with an incorrect use of "it's""
    Applying: Rework linux command
    Applying: Rework linux16 command
    Applying: re-write .gitignore
    Applying: IBM client architecture (CAS) reboot support
    Applying: for ppc, reset console display attr when clear screen
    Applying: Disable GRUB video support for IBM power machines
    Applying: Move bash completion script (#922997)
    Applying: Allow "fallback" to include entries by title, not just number.
    Applying: Make "exit" take a return code.
    Applying: Make efi machines load an env block from a variable
    Applying: Migrate PPC from Yaboot to Grub2
    Applying: Add fw_path variable (revised)
    Applying: Pass "\x[[:hex:]][[:hex:]]" straight through unmolested.
    Applying: blscfg: add blscfg module to parse Boot Loader Specification snippets
    Applying: Add devicetree loading
    Applying: Enable pager by default. (#985860)
    Applying: Don't say "GNU/Linux" in generated menus.
    Applying: Add .eh_frame to list of relocations stripped
    Applying: Don't require a password to boot entries generated by grub-mkconfig.
    Applying: use fw_path prefix when fallback searching for grub config
    Applying: Try mac/guid/etc before grub.cfg on tftp config files.
    Applying: Generate OS and CLASS in 10_linux from /etc/os-release
    Applying: Try $prefix if $fw_path doesn't work.
    Applying: Make grub2-mkconfig construct titles that look like the ones we want elsewhere.
    Applying: Add friendly grub2 password config tool (#985962)
    Applying: tcp: add window scaling support
    Applying: efinet and bootp: add support for dhcpv6
    Applying: bootp: New net_bootp6 command
    Applying: Add grub-get-kernel-settings and use it in 10_linux
    Applying: Make grub_fatal() also backtrace.
    Applying: Make our info pages say "grub2" where appropriate.
    Patch failed at 0032 Make our info pages say "grub2" where appropriate.
    hint: Use 'git am --show-current-patch=diff' to see the failed patch
    hint: When you have resolved this problem, run "git am --continue".
    hint: If you prefer to skip this patch, run "git am --skip" instead.
    hint: To restore the original branch and stop patching, run "git am --abort".
    hint: Disable this message with "git config set advice.mergeConflict false"
    error: Bad exit status from /var/tmp/rpm-tmp.7SswhI (%prep)
    RPM build errors:
        %changelog not in descending chronological order
        Bad exit status from /var/tmp/rpm-tmp.7SswhI (%prep)
    Child return code was: 1

Fixes: AB#20278