specs: fix rpmspec error
With newer rpm build tools (4.16+), rpmspec now requires that no bare words are
in the spec. See the following error message:

WARN[0003] error: bare words are no longer supported, please use "...":  aarch64 != x86_64
error:                                                        ^
error: /specs/gcc-bootstrap_cross/gcc-bootstrap_cross.spec:34: bad %if condition:  aarch64 != x86_64
error: query of specfile /specs/gcc-bootstrap_cross/gcc-bootstrap_cross.spec failed, can't parse

See the following thread: https://www.spinics.net/lists/fedora-devel/msg268642.html

Signed-off-by: Chris Co <chrco@microsoft.com>